import { WorkoutSession } from '../types';

export class CalendarExportService {
  /**
   * Generates an iCalendar (.ics) string for a list of scheduled workouts
   */
  static generateICS(workouts: WorkoutSession[]): string {
    const now = new Date();
    const pad = (n: number) => (n < 10 ? `0${n}` : `${n}`);
    const formatDate = (d: Date) =>
      `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}00Z`;

    let ics = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//JARVIS Adaptive Personal Trainer//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:JARVIS Training Schedule',
      'X-WR-TIMEZONE:UTC',
    ];

    workouts.forEach((workout, idx) => {
      // Schedule each day starting tomorrow morning at 07:00
      const startDate = new Date();
      startDate.setDate(startDate.getDate() + idx);
      startDate.setHours(7, 30, 0, 0);

      const endDate = new Date(startDate);
      endDate.setMinutes(endDate.getMinutes() + (workout.estimatedDurationMinutes || 50));

      const exercisesSummary = workout.exercises
        .map(
          (e, i) =>
            `${i + 1}. ${e.name} (${e.targetSets} sets x ${e.targetReps} reps @ ${e.recommendedLoad}kg)`
        )
        .join('\\n');

      const description = `JARVIS Workout: ${workout.title}\\nFocus: ${workout.focus}\\nDuration: ${workout.estimatedDurationMinutes} mins\\n\\nPrescribed Exercises:\\n${exercisesSummary}\\n\\nGenerated by JARVIS Adaptive Personal Trainer.`;

      ics.push(
        'BEGIN:VEVENT',
        `UID:jarvis-workout-${workout.id}-${idx}@jarvis.fitness`,
        `DTSTAMP:${formatDate(now)}`,
        `DTSTART:${formatDate(startDate)}`,
        `DTEND:${formatDate(endDate)}`,
        `SUMMARY:🏋️‍♂️ JARVIS: ${workout.title}`,
        `DESCRIPTION:${description}`,
        'STATUS:CONFIRMED',
        'BEGIN:VALARM',
        'TRIGGER:-PT15M',
        'ACTION:DISPLAY',
        'DESCRIPTION:Workout reminder: JARVIS training session in 15 minutes',
        'END:VALARM',
        'END:VEVENT'
      );
    });

    ics.push('END:VCALENDAR');
    return ics.join('\r\n');
  }

  /**
   * Triggers download of the .ics file on the device
   */
  static downloadCalendarFile(workouts: WorkoutSession[], filename: string = 'jarvis-training-schedule.ics'): void {
    const icsContent = this.generateICS(workouts);
    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
